### ISSUE TITLE
CIFAR, TestStudent benchmarks not running 

### ISSUE THREAD

**Issue by leggerf** [Open-ForBC/OpenForBC-Benchmark#182]
missing requirement?

```
legger@laptop-fede:~/OpenForBC-Benchmark$ o4bc-bench benchmark run CIFAR_realtime_benchmark
Running "CIFAR_realtime_benchmark" setup commands
$ python3 -m venv .venv
(venv) $ ./setup.sh
Collecting tensorflow-gpu (from -r ./requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/76/04/43153bfdfcf6c9a4c38ecdb971ca9a75b9a791bb69a764d652c359aca504/tensorflow_gpu-1.14.0-cp36-cp36m-manylinux1_x86_64.whl (377.0MB)
⠏ CIFAR_realtime_benchmark(setup): ./setup.sh
Collecting sklearn (from -r ./requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/1e/7a/dbb3be0ce9bd5c8b7e3d87328e79063f8b263b2b1bfa4774cb1147bfcd3f/sklearn-0.0.tar.gz
Collecting gputil (from -r ./requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/ed/0e/5c61eedde9f6c87713e89d794f01e378cfd9565847d4576fa627d758c554/GPUtil-1.4.0.tar.gz
Collecting numpy==1.21 (from -r ./requirements.txt (line 4))
  Could not find a version that satisfies the requirement numpy==1.21 (from -r ./requirements.txt (line 4)) (from versions: 1.3.0, 1.4.1, 1.5.0, 1.5.1, 1.6.0, 1.6.1, 1.6.2, 1.7.0, 1.7.1, 1.7.2, 1.8.0, 1.8.1, 1.8.2, 1.9.0, 1.9.1, 1.9.2, 1.9.3, 1.10.0.post2, 1.10.1, 1.10.2, 1.10.4, 1.11.0, 1.11.1, 1.11.2, 1.11.3, 1.12.0, 1.12.1, 1.13.0rc1, 1.13.0rc2, 1.13.0, 1.13.1, 1.13.3, 1.14.0rc1, 1.14.0, 1.14.1, 1.14.2, 1.14.3, 1.14.4, 1.14.5, 1.14.6, 1.15.0rc1, 1.15.0rc2, 1.15.0, 1.15.1, 1.15.2, 1.15.3, 1.15.4, 1.16.0rc1, 1.16.0rc2, 1.16.0, 1.16.1, 1.16.2, 1.16.3, 1.16.4, 1.16.5, 1.16.6, 1.17.0rc1, 1.17.0rc2, 1.17.0, 1.17.1, 1.17.2, 1.17.3, 1.17.4, 1.17.5, 1.18.0rc1, 1.18.0, 1.18.1, 1.18.2, 1.18.3, 1.18.4, 1.18.5, 1.19.0rc1, 1.19.0rc2, 1.19.0, 1.19.1, 1.19.2, 1.19.3, 1.19.4, 1.19.5)
No matching distribution found for numpy==1.21 (from -r ./requirements.txt (line 4))
Running "CIFAR_realtime_benchmark" preset "training"
(venv) $ ./CIFAR_realtime.py gpu training
Traceback (most recent call last):
  File "./CIFAR_realtime.py", line 21, in <module>
    import nvidia_smi
ModuleNotFoundError: No module named 'nvidia_smi'
Benchmark "CIFAR_realtime_benchmark" preset "training" command "./CIFAR_realtime.py gpu training" failed
Task (venv) $ ./CIFAR_realtime.py gpu training failed with return code 1
ERROR: Benchmark "CIFAR_realtime_benchmark" failed
```

**Comment by leggerf** [comment]
same error from Teacher STudent

```
Collecting numpy==1.21 (from -r ./requirements.txt (line 4))
  Could not find a version that satisfies the requirement numpy==1.21 (from -r ./requirements.txt (line 4)) (from versions: 1.3.0, 1.4.1, 1.5.0, 1.5.1, 1.6.0, 1.6.1, 1.6.2, 1.7.0, 1.7.1, 1.7.2, 1.8.0, 1.8.1, 1.8.2, 1.9.0, 1.9.1, 1.9.2, 1.9.3, 1.10.0.post2, 1.10.1, 1.10.2, 1.10.4, 1.11.0, 1.11.1, 1.11.2, 1.11.3, 1.12.0, 1.12.1, 1.13.0rc1, 1.13.0rc2, 1.13.0, 1.13.1, 1.13.3, 1.14.0rc1, 1.14.0, 1.14.1, 1.14.2, 1.14.3, 1.14.4, 1.14.5, 1.14.6, 1.15.0rc1, 1.15.0rc2, 1.15.0, 1.15.1, 1.15.2, 1.15.3, 1.15.4, 1.16.0rc1, 1.16.0rc2, 1.16.0, 1.16.1, 1.16.2, 1.16.3, 1.16.4, 1.16.5, 1.16.6, 1.17.0rc1, 1.17.0rc2, 1.17.0, 1.17.1, 1.17.2, 1.17.3, 1.17.4, 1.17.5, 1.18.0rc1, 1.18.0, 1.18.1, 1.18.2, 1.18.3, 1.18.4, 1.18.5, 1.19.0rc1, 1.19.0rc2, 1.19.0, 1.19.1, 1.19.2, 1.19.3, 1.19.4, 1.19.5)
No matching distribution found for numpy==1.21 (from -r ./requirements.txt (line 4))
Running "TeacherStudent_realtime_benchmark" preset "inference"
(venv) $ ./TeacherStudent_realtime.py gpu inference
Traceback (most recent call last):
  File "./TeacherStudent_realtime.py", line 18, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
Benchmark "TeacherStudent_realtime_benchmark" preset "inference" command "./TeacherStudent_realtime.py gpu inference" failed
Task (venv) $ ./TeacherStudent_realtime.py gpu inference failed with return code 1
ERROR: Benchmark "TeacherStudent_realtime_benchmark" failed
```

**Comment by gabrielefronze** [comment]
Should be fixed by https://github.com/Open-ForBC/OpenForBC-Benchmark/pull/185
