### ISSUE TITLE
MNIST benchmark fails with bdist_wheel error

### ISSUE THREAD

**Issue by leggerf** [Open-ForBC/OpenForBC-Benchmark#184]
` o4bc-bench benchmark run MNIST_FCNeuralNetwork `

gives this error:

```
  Running setup.py bdist_wheel for sklearn: finished with status 'error'
  Complete output from command /home/legger/OpenForBC-Benchmark/benchmarks/MNIST_FCNeuralNetwork/.venv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-5oj35ykm/sklearn/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpvyn3i405pip-wheel- --python-tag cp36:
  Failed building wheel for sklearn
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help

  error: invalid command 'bdist_wheel'

  ----------------------------------------
  Running setup.py clean for sklearn
  Running setup.py bdist_wheel for grpcio: started
  Running setup.py bdist_wheel for grpcio: finished with status 'error'
  Complete output from command /home/legger/OpenForBC-Benchmark/benchmarks/MNIST_FCNeuralNetwork/.venv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-5oj35ykm/grpcio/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpowpo7xtepip-wheel- --python-tag cp36:
  Found cython-generated files...
  Failed building wheel for grpcio
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help

  error: invalid command 'bdist_wheel'

  ----------------------------------------
  Running setup.py clean for grpcio
  Running setup.py bdist_wheel for pillow: started
  Running setup.py bdist_wheel for pillow: finished with status 'error'
  Complete output from command /home/legger/OpenForBC-Benchmark/benchmarks/MNIST_FCNeuralNetwork/.venv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-5oj35ykm/pillow/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpkay_fd_kpip-wheel- --python-tag cp36:
  Failed building wheel for pillow
  /usr/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
    warnings.warn(msg)
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help

  error: invalid command 'bdist_wheel'

  ----------------------------------------
```

and finally fails with

```
3.6/grpc/_cython/cygrpc.cpython-36m-x86_64-linux-gnu.so -lpthread -static-libgcc
    Traceback (most recent call last):
      File "/tmp/pip-build-5oj35ykm/grpcio/src/python/grpcio/commands.py", line 280, in build_extensions
        build_ext.build_ext.build_extensions(self)
      File "/usr/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
        self._build_extensions_serial()
      File "/usr/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
Command "/home/legger/OpenForBC-Benchmark/benchmarks/MNIST_FCNeuralNetwork/.venv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-5oj35ykm/grpcio/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-r33x0r02-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/legger/OpenForBC-Benchmark/benchmarks/MNIST_FCNeuralNetwork/.venv/include/site/python3.6/grpcio" failed with error code 1 in /tmp/pip-build-5oj35ykm/grpcio/
        self.build_extension(ext)
      File "/home/legger/OpenForBC-Benchmark/benchmarks/MNIST_FCNeuralNetwork/.venv/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 200, in build_extension
        if ext._needs_stub:
    AttributeError: 'Extension' object has no attribute '_needs_stub'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-5oj35ykm/grpcio/setup.py", line 544, in <module>
        cmdclass=COMMAND_CLASS,
      File "/home/legger/OpenForBC-Benchmark/benchmarks/MNIST_FCNeuralNetwork/.venv/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/legger/OpenForBC-Benchmark/benchmarks/MNIST_FCNeuralNetwork/.venv/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.6/distutils/command/install.py", line 589, in run
        self.run_command('build')
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/legger/OpenForBC-Benchmark/benchmarks/MNIST_FCNeuralNetwork/.venv/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 78, in run
        _build_ext.run(self)
      File "/usr/lib/python3.6/distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/tmp/pip-build-5oj35ykm/grpcio/src/python/grpcio/commands.py", line 283, in build_extensions
        support.diagnose_build_ext_error(self, error, formatted_exception)
      File "/tmp/pip-build-5oj35ykm/grpcio/src/python/grpcio/support.py", line 117, in diagnose_build_ext_error
        diagnostic(build_ext, error)
      File "/tmp/pip-build-5oj35ykm/grpcio/src/python/grpcio/support.py", line 97, in diagnose_attribute_error
        "We expect a missing `_needs_stub` attribute from older versions of "
    commands.CommandError: We expect a missing `_needs_stub` attribute from older versions of setuptools. Consider upgrading setuptools.

    ----------------------------------------
Running "MNIST_FCNeuralNetwork" preset "gpu_shallow_largebatch"
(venv) $ ./MNIST_FCNeuralNetwork_benchmark.py gpu 1000 1024
Traceback (most recent call last):
  File "./MNIST_FCNeuralNetwork_benchmark.py", line 3, in <module>
    import tensorflow as tf
ModuleNotFoundError: No module named 'tensorflow'
Benchmark "MNIST_FCNeuralNetwork" preset "gpu_shallow_largebatch" command "./MNIST_FCNeuralNetwork_benchmark.py gpu 1000 1024" failed
Task (venv) $ ./MNIST_FCNeuralNetwork_benchmark.py gpu 1000 1024 failed with return code 1
ERROR: Benchmark "MNIST_FCNeuralNetwork" failed
```

**Comment by iH8c0ff33** [comment]
sklearn version 1.0 requires python 3.7 or newer.

We should add this requirement to the benchmark's README or use an older version.
Compatibility with 3.7 will need to be tested after #186 is closed.

**Comment by iH8c0ff33** [comment]
Should we require python 3.9 for the o4bc-bench tool? Or just for some
benchmarks?

**Comment by leggerf** [comment]
works with python 3.9. Dropping compatibility with 3.7. Closing

**Comment by leggerf** [comment]
my 2 c/s, I'd go for 3.9

It's frustrating to setup everything for 3.7, and then find out that 
some benchmarks need 3.9

OTOH, if it's only ONE benchmark, then it might make sense to keep 
compatibility with 3.7


Il 23/03/2022 18:22, Daniele Monteleone ha scritto:
