### ISSUE TITLE
None of the standalone benchmarks work

### ISSUE THREAD

**Issue by leggerf** [Open-ForBC/OpenForBC-Benchmark#41]
Error:

💻 Select Benchmark  done
Traceback (most recent call last):
  File "user_interfaces/cli.py", line 291, in <module>
    app()
  File "/usr/local/lib/python3.8/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/typer/main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "user_interfaces/cli.py", line 167, in interactive
    InteractiveMenu().runner()
  File "user_interfaces/cli.py", line 112, in runner
    raise Exception("EmptyBenchmarkList")
Exception: EmptyBenchmarkList

**Comment by aneesh404** [comment]
Hi @leggerf , in the case of running stand-alone benchmarks, you need to select one/ more than one benchmarks that you wish to run by pressing spacebar. Once you're done selecting then proceed by pressing enter.

**Comment by leggerf** [comment]
@aneesh404 a few comments:
1. using space to select the benchmarks is not so intuitive, since in all other menus we use enter. I suggest to use enter to select them, and then x to run it. 
2. This should also be documented in the CLI, atm I see only <space> to select, but no indication how to run it.
3.  if no benchmark is selected and one tries to run (as I did) an empty list of benchmark, the CLI should throw a meaningful error and ask to select a benchmark.

**Comment by aneesh404** [comment]
1. @leggerf I realized that it was a design flaw and I think if user wants to run several benchmarks back-to-back, they can make a suite/ run a pre-built suite. Would that be a better option? Should stand alone benchmark be a single-benchmark-run only? 
2. It's actually in the interactive menu when you reach that prompt. Probably not that evident.
3. I'll look into that, for me it's showing the folowing error message.
<details open>
<summary>Error message</summary>
<br>
  File "/home/deathstar/Documents/OpenForBC-Benchmark/user_interfaces/cli.py", line 114, in runner
<br>
    raise EmptyBenchmarkList
<br>
user_interfaces.utils.EmptyBenchmarkList: Please select benchmark(s) to run by pressing spacebar to select.
</details>

**Comment by leggerf** [comment]
1. yes, indeed. Pls fix it so that in Standalone one can run only one benchmark
2. when 1. is implemented, this will be fixed too
3. I checked again, and I get the error I posted above...maybe this is fixed in one of the other PRs that are still open?
